# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_machine_status',
            name='MACHINE_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.T_PROD_MACHINE'),
        ),
    ]
